package ru.vagapov.userapi.dao.Impl;

import ru.vagapov.userapi.dao.UserDao;
import ru.vagapov.userapi.entity.UserEntity;
import ru.vagapov.userapi.util.ConnectionUtil;

import java.sql.*;
import java.time.Instant;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;

public class UserDaoJDBCImpl implements UserDao {
    public ConnectionUtil conUtil = new ConnectionUtil();


    public UserDaoJDBCImpl() {
            
    }

    public void createUsersTable() {
        try (Connection con = conUtil.getConnection()){
            String s = " CREATE TABLE IF NOT EXISTS users (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "firstName VARCHAR(255) NOT NULL," +
                    "lastName VARCHAR(255) NOT NULL ," +
                    "birthDate TIMESTAMP," +
                    "birthPlace  VARCHAR(255) NOT NULL," +
                    "age SMALLINT)";
            Statement stm = con.createStatement();
            stm.execute(s);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void dropUsersTable() {
        try(Connection con = conUtil.getConnection()) {
            String s = "DROP TABLE IF EXISTS users";
            Statement stm = con.createStatement();
            stm.execute(s);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void saveUser(String firstName,
                         String lastName,
                         LocalDate birthDate,
                         String birthPlace,
                         Byte age) {
        try (Connection con = conUtil.getConnection()){
            String s = "INSERT INTO users ( firstName, lastName, birthDate, birthPlace, age) VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement pstm = con.prepareStatement(s);

            pstm.setString(1, firstName);
            pstm.setString(2, lastName);
            pstm.setDate(3, Date.valueOf(birthDate));
            pstm.setString(4, birthPlace);
            pstm.setByte(5, age);
            pstm.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void removeUserById(Long id) {
        try(Connection con = conUtil.getConnection()) {
            String s = "DELETE FROM users WHERE id=?";
            PreparedStatement pstm = con.prepareStatement(s);
            pstm.setLong(1, id);
            pstm.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public List<UserEntity> getAllUsers() {
        List<UserEntity> userEntityList = new ArrayList<>();
        try(Connection con = conUtil.getConnection()){
            String s = "SELECT * FROM users";
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(s);
            while (rs.next()) {
                UserEntity user = new UserEntity();
                user.setId(rs.getLong(1));
                user.setFirstName(rs.getString(2));
                user.setLastName(rs.getString(3));
                user.setBirthDate(OffsetDateTime.ofInstant(Instant.ofEpochMilli(rs.getDate(4).getTime()), ZoneId.of("UTC")));
                user.setBirthPlace(rs.getString(5));
                user.setAge(rs.getByte(6));
                userEntityList.add(user);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        return userEntityList;
    }

    public void cleanUsersTable() {
        String s = "TRUNCATE TABLE users";
        try(Connection con = conUtil.getConnection()) {
            Statement stm = con.createStatement();
            stm.execute(s);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

}
