package ru.vagapov.userapi.service.impl;

import ru.vagapov.userapi.dao.Impl.UserDaoJDBCImpl;
import ru.vagapov.userapi.dao.UserDao;
import ru.vagapov.userapi.entity.UserEntity;
import ru.vagapov.userapi.service.UserService;
import ru.vagapov.userapi.util.ConnectionUtil;

import java.sql.*;
import java.time.*;
import java.util.ArrayList;
import java.util.List;

public class UserServiceImpl extends ConnectionUtil implements UserService {
    Connection con = getConnection();

    public UserServiceImpl(UserDao userDao) {
    }

    public void createUsersTable() {
        try {
            String s = " Create table if not exists users (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "firstName VARCHAR(255) NOT NULL," +
                    "lastName VARCHAR(255) NOT NULL ," +
                    "birthDate TIMESTAMP," +
                    "birthPlace  VARCHAR(255) NOT NULL," +
                    "age SMALLINT)";
            Statement sql = con.createStatement();
            sql.execute(s);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    public void dropUsersTable() {

        try {
            String s = "DROP table if exists users";
            Statement sql = con.createStatement();
            sql.execute(s);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    public void saveUser(
            String firstName,
            String lastName,
            LocalDate birthDate,
            String birthPlace,
            Byte age) {
        try {
            String s = "INSERT INTO users ( firstName, lastName, birthDate, birthPlace, age) VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement sql = con.prepareStatement(s);

            sql.setString(1, firstName);
            sql.setString(2, lastName);
            sql.setDate(3, Date.valueOf(birthDate));
            sql.setString(4, birthPlace);
            sql.setByte(5, age);
            sql.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    public void removeUserById(Long id) {
        try {
            String s = "Delete from users where id=?";
            PreparedStatement sql = con.prepareStatement(s);
            sql.setLong(1, id);
            sql.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }


    }

    public List<UserEntity> getAllUsers() {
        List<UserEntity> userEntityList = new ArrayList<>();
        try {
            String s = "Select * from users";
            Statement sql = con.createStatement();
            ResultSet rs = sql.executeQuery(s);
            while (rs.next()) {
                UserEntity user = new UserEntity();
                user.setId(rs.getLong(1));
                user.setFirstName(rs.getString(2));
                user.setLastName(rs.getString(3));
                user.setBirthDate(OffsetDateTime.ofInstant(Instant.ofEpochMilli(rs.getDate(4).getTime()), ZoneId.of("UTC")));
                user.setBirthPlace(rs.getString(5));
                user.setAge(rs.getByte(6));
                userEntityList.add(user);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        return userEntityList;
    }

    public void cleanUsersTable() {
        String s = "Truncate table users";
        try {
            Statement sql = con.createStatement();
            sql.execute(s);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }


    }
}
